# Project information
site_name: A Guide To All Things Internships
site_description: 'A guide to all things internships'
site_author: 'Evy Kassirer'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/evykassirer/playing-the-internship-game'

# Copyright
copyright: Â© Evy Kassirer

# Documentation and theme
theme: 'readthedocs'

# Options
extra:
  author:
    github: 'evykassirer'


# Extensions
markdown_extensions:
  - admonition
